# Generated by Django 4.2.16 on 2026-06-04 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkBuyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(choices=[('chick_mash', 'Chick Mash'), ('growers_mash', 'Growers Mash'), ('layers_mash', 'Layers Mash'), ('layers_pellets', 'Layers Pellets'), ('concentrates', 'Concentrates')], max_length=30)),
                ('target_bags', models.PositiveIntegerField(help_text='Total 50kg bags needed')),
                ('target_date', models.DateField()),
                ('pickup_location', models.CharField(max_length=300)),
                ('county', models.CharField(default='nairobi', max_length=50)),
                ('max_members', models.PositiveSmallIntegerField(default=20)),
                ('status', models.CharField(choices=[('open', 'Open — accepting members'), ('confirmed', 'Confirmed — purchasing soon'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('estimated_saving_pct', models.DecimalField(decimal_places=1, default=10, max_digits=4)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organised_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalFeedPrice',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('feed_type', models.CharField(choices=[('chick_mash', 'Chick Mash'), ('growers_mash', 'Growers Mash'), ('layers_mash', 'Layers Mash'), ('layers_pellets', 'Layers Pellets'), ('concentrates', 'Concentrates')], max_length=30)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('price_per_50kg', models.DecimalField(decimal_places=2, help_text='KES per 50kg bag', max_digits=8)),
                ('location', models.CharField(max_length=200)),
                ('county', models.CharField(default='nairobi', max_length=50)),
                ('date_observed', models.DateField()),
                ('verified', models.BooleanField(default=False)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='feed_watch.feedsupplier')),
            ],
            options={
                'verbose_name': 'historical feed price',
                'verbose_name_plural': 'historical feed prices',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FeedPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(choices=[('chick_mash', 'Chick Mash'), ('growers_mash', 'Growers Mash'), ('layers_mash', 'Layers Mash'), ('layers_pellets', 'Layers Pellets'), ('concentrates', 'Concentrates')], max_length=30)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('price_per_50kg', models.DecimalField(decimal_places=2, help_text='KES per 50kg bag', max_digits=8)),
                ('location', models.CharField(max_length=200)),
                ('county', models.CharField(default='nairobi', max_length=50)),
                ('date_observed', models.DateField()),
                ('verified', models.BooleanField(default=False)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_prices', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed_watch.feedsupplier')),
            ],
            options={
                'ordering': ['-date_observed', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkBuyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bags_needed', models.PositiveSmallIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='feed_watch.bulkbuygroup')),
            ],
            options={
                'unique_together': {('group', 'farmer')},
            },
        ),
    ]
