# Generated by Django 4.2.16 on 2026-06-04 10:44

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('county', models.CharField(choices=[('nairobi', 'Nairobi'), ('kiambu', 'Kiambu'), ('kajiado', 'Kajiado'), ('machakos', 'Machakos'), ('muranga', "Murang'a")], default='nairobi', max_length=50)),
                ('sub_location', models.CharField(blank=True, max_length=100)),
                ('farm_scale', models.CharField(choices=[('small', 'Small (< 500 birds)'), ('medium', 'Medium (500–2,000 birds)'), ('large', 'Large (> 2,000 birds)')], default='small', max_length=20)),
                ('total_birds', models.PositiveIntegerField(default=0)),
                ('profile_complete', models.BooleanField(default=False)),
                ('sms_alerts', models.BooleanField(default=True, help_text='Receive SMS disease alerts')),
                ('joined_cooperative', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Farmer',
                'verbose_name_plural': 'Farmers',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FarmRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('eggs_produced', models.PositiveIntegerField(default=0)),
                ('eggs_sold', models.PositiveIntegerField(default=0)),
                ('revenue_kes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('feed_cost_kes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mortality', models.PositiveSmallIntegerField(default=0, help_text='Birds lost this week')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('farmer', 'week_start')},
            },
        ),
    ]
