# Generated by Django 4.2.16 on 2026-06-04 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('swahili_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('symptoms', models.TextField(help_text='Comma-separated list of symptoms')),
                ('prevention', models.TextField()),
                ('treatment', models.TextField()),
                ('emergency_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='diseases/')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=200)),
                ('supplier', models.CharField(max_length=200)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('birds_vaccinated', models.PositiveIntegerField()),
                ('date_administered', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='farm_guard.disease')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_administered'],
            },
        ),
        migrations.CreateModel(
            name='SymptomCheckerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms_reported', models.TextField()),
                ('vet_referral_triggered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('suggested_disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm_guard.disease')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name_freetext', models.CharField(blank=True, help_text='If disease unknown', max_length=200)),
                ('county', models.CharField(default='nairobi', max_length=50)),
                ('sub_location', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('birds_affected', models.PositiveIntegerField(default=0)),
                ('birds_dead', models.PositiveIntegerField(default=0)),
                ('severity', models.CharField(choices=[('suspected', 'Suspected — not confirmed'), ('confirmed', 'Confirmed by vet'), ('resolved', 'Resolved')], default='suspected', max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='alerts/')),
                ('verified_by_vet', models.BooleanField(default=False)),
                ('sms_broadcast_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm_guard.disease')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
