# Generated by Django 4.2.16 on 2026-06-04 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('A', 'Grade A (Large)'), ('B', 'Grade B (Medium)'), ('C', 'Grade C (Small)'), ('mixed', 'Mixed')], max_length=10)),
                ('price_per_tray', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_observed', models.DateField()),
                ('source', models.CharField(default='crowdsourced', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_observed'],
            },
        ),
        migrations.CreateModel(
            name='EggListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'Grade A (Large)'), ('B', 'Grade B (Medium)'), ('C', 'Grade C (Small)'), ('mixed', 'Mixed')], max_length=10)),
                ('quantity_trays', models.PositiveIntegerField(help_text='Number of 30-egg trays available')),
                ('price_per_tray', models.DecimalField(decimal_places=2, help_text='KES per tray', max_digits=8)),
                ('available_from', models.DateField()),
                ('available_until', models.DateField()),
                ('delivery_available', models.BooleanField(default=False)),
                ('pickup_location', models.CharField(max_length=300)),
                ('county', models.CharField(default='nairobi', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuyerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_type', models.CharField(choices=[('individual', 'Individual / Household'), ('retailer', 'Retailer / Shop'), ('restaurant', 'Restaurant / Hotel'), ('institution', 'School / Hospital / Institution'), ('wholesaler', 'Wholesaler')], max_length=20)),
                ('buyer_phone', models.CharField(max_length=20)),
                ('buyer_email', models.EmailField(blank=True, max_length=254)),
                ('trays_requested', models.PositiveIntegerField()),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='egg_market.egglisting')),
            ],
        ),
    ]
