# Generated by Django 4.2.16 on 2026-06-04 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('feed', 'Feed Management'), ('health', 'Flock Health'), ('housing', 'Housing & Biosecurity'), ('market', 'Market Access'), ('finance', 'Farm Finance'), ('regulation', 'Regulation & Standards')], max_length=20)),
                ('summary', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('sms_version', models.CharField(blank=True, max_length=160)),
                ('author', models.CharField(default='Platform Team', max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='articles/')),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VetDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(default='Veterinary Officer', max_length=200)),
                ('county', models.CharField(max_length=50)),
                ('sub_location', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('specialisation', models.CharField(blank=True, max_length=200)),
                ('available_for_farm_visits', models.BooleanField(default=True)),
                ('dvs_registered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Vet directory',
            },
        ),
        migrations.CreateModel(
            name='AskExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('answered', 'Answered'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agri_learn.vetdirectory')),
                ('farmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
